"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

export default function BuilderPage() {
  const [targetUrl, setTargetUrl] = useState<string>("");
    const [selectedStyle, setSelectedStyle] = useState<string>("modern");
      const [isLoading, setIsLoading] = useState(true);
        const [previewUrl, setPreviewUrl] = useState<string>("");
          const [progress, setProgress] = useState<string>("Initializing...");
            const [generatedCode, setGeneratedCode] = useState<string>("");
              const router = useRouter();

                useEffect(() => {
                    const url = sessionStorage.getItem('targetUrl');
                        const style = sessionStorage.getItem('selectedStyle');
                            
                                if (!url) {
                                      router.push('/');
                                            return;
                                                }
                                                    
                                                        setTargetUrl(url);
                                                            setSelectedStyle(style || "modern");
                                                                
                                                                    generateWebsite(url, style || "modern");
                                                                        // eslint-disable-next-line react-hooks/exhaustive-deps
                                                                          }, [router]);

                                                                            const generateWebsite = async (url: string, style: string) => {
                                                                                try {
                                                                                      setProgress("Generating with MAXAAI...");
                                                                                            setIsLoading(true);

                                                                                                  const res = await fetch("/api/generate", {
                                                                                                          method: "POST",
                                                                                                                  headers: {
                                                                                                                            "Content-Type": "application/json",
                                                                                                                                    },
                                                                                                                                            body: JSON.stringify({
                                                                                                                                                      prompt: `Create a ${style} website for ${url}`,
                                                                                                                                                              }),
                                                                                                                                                                    });

                                                                                                                                                                          const data = await res.json();

                                                                                                                                                                                setGeneratedCode(data.generatedHTML);

                                                                                                                                                                                      setPreviewUrl(
                                                                                                                                                                                              "data:text/html;charset=utf-8," +
                                                                                                                                                                                                        encodeURIComponent(data.generatedHTML)
                                                                                                                                                                                                              );

                                                                                                                                                                                                                    setProgress("Website ready!");
                                                                                                                                                                                                                          setIsLoading(false);
                                                                                                                                                                                                                                toast.success("Website generated successfully!");

                                                                                                                                                                                                                                    } catch (error) {
                                                                                                                                                                                                                                          console.error("Error generating website:", error);
                                                                                                                                                                                                                                                toast.error("Failed to generate website. Please try again.");
                                                                                                                                                                                                                                                      setProgress("Error occurred");
                                                                                                                                                                                                                                                            setTimeout(() => router.push('/'), 2000);
                                                                                                                                                                                                                                                                  setIsLoading(false);
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                        };

                                                                                                                                                                                                                                                                          const downloadCode = () => {
                                                                                                                                                                                                                                                                              const blob = new Blob([generatedCode], { type: 'text/html' });
                                                                                                                                                                                                                                                                                  const url = URL.createObjectURL(blob);
                                                                                                                                                                                                                                                                                      const a = document.createElement('a');
                                                                                                                                                                                                                                                                                          a.href = url;
                                                                                                                                                                                                                                                                                              a.download = 'website.html';
                                                                                                                                                                                                                                                                                                  document.body.appendChild(a);
                                                                                                                                                                                                                                                                                                      a.click();
                                                                                                                                                                                                                                                                                                          document.body.removeChild(a);
                                                                                                                                                                                                                                                                                                              URL.revokeObjectURL(url);
                                                                                                                                                                                                                                                                                                                  toast.success("Code downloaded!");
                                                                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                          <div className="min-h-screen bg-background-base">
                                                                                                                                                                                                                                                                                                                                <div className="flex h-screen">
                                                                                                                                                                                                                                                                                                                                        {/* Sidebar */}
                                                                                                                                                                                                                                                                                                                                                <div className="w-80 bg-white border-r border-border-faint p-24 flex flex-col">
                                                                                                                                                                                                                                                                                                                                                          <h2 className="text-title-small font-semibold mb-16">Building Your Website</h2>
                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                              <div className="space-y-12 flex-1">
                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-label-small text-black-alpha-56 mb-4">Target URL</div>
                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-body-medium text-accent-black truncate">{targetUrl}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-label-small text-black-alpha-56 mb-4">Style</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-body-medium text-accent-black capitalize">{selectedStyle}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="text-label-small text-black-alpha-56 mb-4">Status</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="text-body-medium text-heat-100">{progress}</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-8">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {!isLoading && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClick={downloadCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full py-12 px-16 bg-heat-100 hover:bg-heat-200 text-white rounded-10 text-label-medium transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Download Code
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        onClick={() => router.push('/')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="w-full py-12 px-16 bg-black-alpha-4 hover:bg-black-alpha-6 rounded-10 text-label-medium transition-all"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Start Over
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Preview */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="flex-1 bg-gray-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {isLoading ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="flex items-center justify-center h-full">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="w-48 h-48 border-4 border-heat-100 border-t-transparent rounded-full animate-spin mb-16 mx-auto"></div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-body-large text-black-alpha-56">{progress}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          previewUrl && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <iframe
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        src={previewUrl}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="w-full h-full border-0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        title="Website Preview"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }